In [2]:
import numpy as np

**NORMALIZATION PROBLEM:** create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normalized.npy

In [8]:
# Create a random 5x5 ndarray
X = np.random.rand(5, 5)  # values between 0 and 1

# Compute mean and standard deviation
mean = X.mean()
std = X.std()

# Normalize using formula Z = (X - mean) / std
X_normalized = (X - mean) / std

# Save the normalized array as 'X_normalized.npy'
np.save("X_normalized.npy", X_normalized)

# Print to check
print("Original X:\n", X)
print("\nMean:", mean, "Std Dev:", std)
print("\nNormalized X:\n", X_normalized)

Original X:
 [[0.55990655 0.79815786 0.16930093 0.23565309 0.00432324]
 [0.31278359 0.72856666 0.14432395 0.54711535 0.62752715]
 [0.50547108 0.31491318 0.74408737 0.72538186 0.43248423]
 [0.25904355 0.97771564 0.58627315 0.70143114 0.431165  ]
 [0.67036215 0.66852519 0.68957223 0.95218642 0.87727439]]

Mean: 0.5465417989708513 Std Dev: 0.25487020345776323

Normalized X:
 [[ 0.05243747  0.98723216 -1.48012935 -1.21979227 -2.12743016]
 [-0.9171657   0.71418651 -1.57812816  0.00225036  0.31775134]
 [-0.16114367 -0.90881013  0.77508302  0.70169075 -0.44751237]
 [-1.12801827  1.69173893  0.15588859  0.60771853 -0.45268845]
 [ 0.4858173   0.47860986  0.56118932  1.59157332  1.29765107]]


**DIVISIBLE BY 3 PROBLEM:** create a 10x10 ndarray with the squares of the first 100 integers and then print the numbers that are divisible by 3

In [6]:
# Generate squares of first 100 positive integers
squares = np.arange(1, 101) ** 2   # from 1^2 to 100^2

# Reshape into a 10x10 ndarray
A = squares.reshape(10, 10)

# Find elements divisible by 3
div_by_3 = A[A % 3 == 0]

# Save results
np.save("div_by_3.npy", div_by_3)

# Print to check
print("10x10 Array A:\n", A)
print("\nElements divisible by 3:\n", div_by_3)

10x10 Array A:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
